### ISSUE TITLE
Selection bug

### ISSUE THREAD

**Issue by check-your-posture** [check-your-posture/simgame#2]
So I just randomly found a bug with the selection/selected entities list(?) whereby after selecting a group of entities, reselecting one of them (and thereby deselecting the rest), and dragging it over other previously selected entities, it reselects them (seemingly reselecting the nearest one at the end of the drag most of the time, sometimes selecting a bunch of them). Bear in mind I haven't tried reproducing this bug with a mouse, so it may be a trackpad-specific problem.
I'll see if I can figure out the source of the bug.

**Comment by jIdle** [comment]
Yeah I'm seeing it now. Was just able to repro it. Seems like the selection rectangle is still active (or being used) somehow while dragging an entity. Not sure how but looking into it.

**Comment by check-your-posture** [comment]
Most recent PR seems to have solved the bug, can't reproduce it at all anymore so closing issue.
